version: "3.7"
services:
  ganache-stress-test:
    container_name: ganache-stress-test
    build:
      context: .
      dockerfile: docker/ganache-stress-test/Dockerfile
    volumes:
      - ./ganache_data_stress_test:/ganache_data
    ports:
      - 8545:8545
    restart: unless-stopped
