version: "3.7"
services:
  ganache-cli:
    container_name: ganache-cli
    build:
      context: .
      dockerfile: docker/ganache-cli/Dockerfile
    volumes:
      - ganache_data:/ganache_data
    ports:
      - 8545:8545
    restart: unless-stopped

  deploy-registry-contract:
    container_name: deploy-registry-contract
    build:
      context: .
      dockerfile: docker/deploy-registry-contract/Dockerfile
    restart: "no"
    depends_on:
      - ganache-cli
    environment:
      - NETWORK=ganache-cli-docker-compose
volumes:
  ganache_data: