version: "3"
services:
  ganache-cli:
    container_name: ganache-cli
    build:
      context: .
      dockerfile: docker/ganache-cli/Dockerfile
    volumes:
      - ganache_data:/ganache_data
    ports:
      - 8545:8545
    restart: unless-stopped
    
volumes:
  ganache_data: