name: Compile
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  check-docker-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Start container stack
        run: docker-compose up -d

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install npm packages
        run: npm install
      - name: "Static analysis"
        run: npm run lint
      - name: "Compile contracts"
        run: npm run compile
      - name: Run tests with coverage
        run: npm run test:coverage
      - name: Run tests to estimate gas costs
        run: npm run test:gas
        env:
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts
          retention-days: 5
