name: Compile
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  check-docker-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Start container stack
        run: docker-compose up -d

  check-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Start Ganache container
        run: docker-compose up -d ganache-cli
      - name: Install npm packages
        run: npm install
      - name: Deploy contracts
        run: npm run deploy:container

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install npm packages
        run: npm install
      - name: "Static analysis"
        run: npm run lint
      - name: "Compile contracts"
        run: npm run compile
      - name: Run tests with coverage
        run: npm run test:coverage
      - name: Run tests to estimate gas costs
        run: npm run test:gas
        env:
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts
          retention-days: 5

  push-contract-wrappers:
    needs: compile
    runs-on: ubuntu-latest
    env:
      API_TOKEN_GITHUB: ${{ secrets.CI }}
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Set up registry contract repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: registry
      - name: Install npm packages
        working-directory: registry
        run: npm install
      - name: "Compile contracts"
        working-directory: registry
        run: npm run compile

      - name: Set up common repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: GarondEisenfaust/decentralised-scd-registry-common
          path: common
          token: ${{ secrets.CI }}
      - name: "Copy wrappers"
        working-directory: registry
        run: |
          mkdir -p ../common/src/wrappers
          cp -R src/types/* ../common/src/wrappers/

      - name: "Commit and push"
        working-directory: common
        run: |
          git config user.name ${{ secrets.NAME }}
          git config user.email ${{ secrets.EMAIL }}
          git add -A
          git commit -m"Update contract wrappers"
          git push
