name: Compile
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  check-docker-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Start container stack
        run: docker-compose up -d

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install npm packages
        run: npm install
      - name: Start container stack
        run: docker-compose up -d
      - name: Compile Solidity contracts
        run: npm run compile
      - name: Migrate Solidity contracts
        run: npm run migrate
